export const BLOG_POSTS = [
    {
        id: 1,
        category: "HSK Study",
        title: "How to build a weekly HSK vocabulary routine",
        excerpt: "Use short review sessions, example sentences, and spaced repetition to remember Chinese words longer.",
        date: "Jun 12, 2026",
        readTime: "5 min read",
        image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=520&fit=crop&auto=format",
    },
    {
        id: 2,
        category: "Pronunciation",
        title: "Why tones matter more than memorizing pinyin alone",
        excerpt: "Clear tone practice helps listeners understand you faster and prevents common speaking mistakes.",
        date: "Jun 08, 2026",
        readTime: "7 min read",
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=520&fit=crop&auto=format",
    },
    {
        id: 3,
        category: "Grammar",
        title: "Simple Chinese sentence patterns beginners should master",
        excerpt: "Start with practical structures for introductions, opinions, time, location, and everyday questions.",
        date: "May 28, 2026",
        readTime: "4 min read",
        image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=520&fit=crop&auto=format",
    },
    {
        id: 4,
        category: "Conversation",
        title: "Practice topics for your first Mandarin speaking sessions",
        excerpt: "Prepare useful phrases for greetings, hobbies, food, travel, shopping, and asking for help.",
        date: "May 20, 2026",
        readTime: "6 min read",
        image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=520&fit=crop&auto=format",
    },
    {
        id: 5,
        category: "Exam Prep",
        title: "How to review before an HSK mock test",
        excerpt: "Focus on weak vocabulary groups, listening speed, reading timing, and common grammar traps.",
        date: "May 14, 2026",
        readTime: "3 min read",
        image: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800&h=520&fit=crop&auto=format",
    },
    {
        id: 6,
        category: "Learning Tips",
        title: "Using streaks without turning Chinese study into pressure",
        excerpt: "Keep momentum with small daily goals while leaving enough space for review and recovery.",
        date: "May 03, 2026",
        readTime: "5 min read",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=520&fit=crop&auto=format",
    },
];
