spring.application.name=backend

server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

resend.api.key=${RESEND_API_KEY:}
resend.from.email=${RESEND_FROM_EMAIL:sonnhhe189023@fpt.edu.vn}
