spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none

resend.api.key=${RESEND_API_KEY:}
resend.from.email=${RESEND_FROM_EMAIL:sonnhhe189023@fpt.edu.vn}
