import {
    Users,
    Award,
    BarChart2,
    Globe,
    Zap,
    Shield,
} from "lucide-react";


export const NAV_LINKS = [{
        label: "Home",
        path: "/",
    },
    {
        label: "About",
        path: "/about",
    },
    {
        label: "Courses",
        path: "/courses",
    },
    {
        label: "Blog",
        path: "/blog",
    },
    {
        label: "Contact",
        path: "/contact",
    },
];
export const STATS = [{
        value: "120K+",
        label: "Active Learners"
    },
    {
        value: "1,800+",
        label: "Expert Courses"
    },
    {
        value: "98%",
        label: "Satisfaction Rate"
    },
    {
        value: "340+",
        label: "Top Instructors"
    },
];

export const COURSES = [{
        id: 1,
        teacher_id: 2,
        category_id: 1,
        category: "Development",
        title: "Full-Stack Web Dev with React & Node.js",
        description: "Build production-ready web applications with React, Node.js, APIs, authentication, and deployment workflows.",
        instructor: "Minh Tran",
        rating: 4.9,
        students: 14200,
        duration: "48h 30m",
        level: "Intermediate",
        price: 1_290_000,
        thumbnail_url: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=480&h=300&fit=crop&auto=format",
        badge: "Bestseller",
        status: "PUBLISHED",
        created_at: "2026-01-12",
        updated_at: "2026-05-24",
    },
    {
        id: 2,
        teacher_id: 3,
        category_id: 2,
        category: "Design",
        title: "UI/UX Design Mastery: From Figma to Prototype",
        description: "Learn user research, wireframing, interface design, design systems, and interactive prototyping in Figma.",
        instructor: "Linh Nguyen",
        rating: 4.8,
        students: 9800,
        duration: "32h 15m",
        level: "All Levels",
        price: 990_000,
        thumbnail_url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=480&h=300&fit=crop&auto=format",
        badge: "Hot",
        status: "PUBLISHED",
        created_at: "2026-02-03",
        updated_at: "2026-06-02",
    },
    {
        id: 3,
        teacher_id: 4,
        category_id: 3,
        category: "Data Science",
        title: "Machine Learning & AI for Practitioners",
        description: "Practice machine learning fundamentals, model evaluation, feature engineering, and AI workflows with real datasets.",
        instructor: "Duc Le",
        rating: 4.9,
        students: 7400,
        duration: "56h 0m",
        level: "Advanced",
        price: 1_590_000,
        thumbnail_url: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=480&h=300&fit=crop&auto=format",
        badge: "New",
        status: "PUBLISHED",
        created_at: "2026-02-18",
        updated_at: "2026-06-10",
    },
    {
        id: 4,
        teacher_id: 5,
        category_id: 4,
        category: "Business",
        title: "Digital Marketing & Growth Hacking",
        description: "Plan campaigns, optimize conversion funnels, read analytics, and build repeatable growth experiments.",
        instructor: "Thu Pham",
        rating: 4.7,
        students: 11500,
        duration: "24h 45m",
        level: "Beginner",
        price: 790_000,
        thumbnail_url: "https://images.unsplash.com/photo-1432888622747-4eb9a8f5a07d?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1432888622747-4eb9a8f5a07d?w=480&h=300&fit=crop&auto=format",
        badge: "Bestseller",
        status: "PUBLISHED",
        created_at: "2026-03-04",
        updated_at: "2026-04-22",
    },
    {
        id: 5,
        teacher_id: 6,
        category_id: 1,
        category: "Development",
        title: "Mobile App Development with Flutter",
        description: "Create cross-platform mobile apps with Flutter widgets, state management, API integration, and release basics.",
        instructor: "Nam Vo",
        rating: 4.8,
        students: 6100,
        duration: "38h 20m",
        level: "Intermediate",
        price: 1_190_000,
        thumbnail_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=480&h=300&fit=crop&auto=format",
        badge: null,
        status: "PUBLISHED",
        created_at: "2026-03-16",
        updated_at: "2026-05-08",
    },
    {
        id: 6,
        teacher_id: 7,
        category_id: 5,
        category: "Cybersecurity",
        title: "Ethical Hacking & Penetration Testing",
        description: "Understand security testing, common vulnerabilities, reporting, and ethical penetration testing workflows.",
        instructor: "Hung Bui",
        rating: 4.9,
        students: 8300,
        duration: "44h 10m",
        level: "Advanced",
        price: 1_490_000,
        thumbnail_url: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=480&h=300&fit=crop&auto=format",
        badge: "Hot",
        status: "PUBLISHED",
        created_at: "2026-04-01",
        updated_at: "2026-06-15",
    },
    {
        id: 7,
        teacher_id: 8,
        category_id: 6,
        category: "Marketing",
        title: "Content Marketing for Online Education",
        description: "Design content plans, write high-converting educational copy, and measure campaign performance.",
        instructor: "Mai Hoang",
        rating: 4.6,
        students: 5200,
        duration: "20h 30m",
        level: "Beginner",
        price: 690_000,
        thumbnail_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=480&h=300&fit=crop&auto=format",
        badge: null,
        status: "PUBLISHED",
        created_at: "2026-04-12",
        updated_at: "2026-05-18",
    },
    {
        id: 8,
        teacher_id: 9,
        category_id: 3,
        category: "Data Science",
        title: "SQL Analytics and Dashboard Reporting",
        description: "Use SQL to analyze business data, create useful reports, and prepare metrics for dashboards.",
        instructor: "Quang Phan",
        rating: 4.7,
        students: 4700,
        duration: "28h 10m",
        level: "Intermediate",
        price: 890_000,
        thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=480&h=300&fit=crop&auto=format",
        badge: "New",
        status: "PUBLISHED",
        created_at: "2026-04-20",
        updated_at: "2026-06-04",
    },
    {
        id: 9,
        teacher_id: 10,
        category_id: 1,
        category: "Development",
        title: "Java Spring Boot API Development",
        description: "Build REST APIs, authentication, validation, persistence, and production-ready backend services.",
        instructor: "Khanh Nguyen",
        rating: 4.8,
        students: 8900,
        duration: "42h 00m",
        level: "Intermediate",
        price: 1_250_000,
        thumbnail_url: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=480&h=300&fit=crop&auto=format",
        badge: "Bestseller",
        status: "PUBLISHED",
        created_at: "2026-05-02",
        updated_at: "2026-06-12",
    },
    {
        id: 10,
        teacher_id: 11,
        category_id: 2,
        category: "Design",
        title: "Brand Identity Systems for Digital Products",
        description: "Create visual identity, typography rules, color systems, and reusable brand guidelines for product teams.",
        instructor: "Ha Tran",
        rating: 4.6,
        students: 3600,
        duration: "18h 40m",
        level: "All Levels",
        price: 760_000,
        thumbnail_url: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=480&h=300&fit=crop&auto=format",
        badge: null,
        status: "PUBLISHED",
        created_at: "2026-05-09",
        updated_at: "2026-06-01",
    },
    {
        id: 11,
        teacher_id: 12,
        category_id: 4,
        category: "Business",
        title: "Startup Finance and Unit Economics",
        description: "Learn pricing, margin, CAC, LTV, cashflow, and financial models for early-stage digital businesses.",
        instructor: "Bao Le",
        rating: 4.7,
        students: 3100,
        duration: "22h 25m",
        level: "Intermediate",
        price: 940_000,
        thumbnail_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=480&h=300&fit=crop&auto=format",
        badge: "Hot",
        status: "PUBLISHED",
        created_at: "2026-05-17",
        updated_at: "2026-06-13",
    },
    {
        id: 12,
        teacher_id: 13,
        category_id: 5,
        category: "Cybersecurity",
        title: "Security Awareness for Product Teams",
        description: "Identify security risks in product workflows, protect user data, and collaborate better with security teams.",
        instructor: "Ngan Do",
        rating: 4.5,
        students: 2800,
        duration: "16h 15m",
        level: "Beginner",
        price: 590_000,
        thumbnail_url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=480&h=300&fit=crop&auto=format",
        image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=480&h=300&fit=crop&auto=format",
        badge: null,
        status: "PUBLISHED",
        created_at: "2026-05-28",
        updated_at: "2026-06-14",
    },
];

export const FEATURES = [{
        icon: Zap,
        title: "Learn at Your Own Pace",
        desc: "Access courses anytime, anywhere.",
    },
    {
        icon: Award,
        title: "Industry-Recognized Certificates",
        desc: "Earn certificates trusted by top companies.",
    },
    {
        icon: Users,
        title: "Expert Instructors",
        desc: "Learn from practitioners.",
    },
    {
        icon: Globe,
        title: "Multilingual Content",
        desc: "Courses in Vietnamese and English.",
    },
    {
        icon: BarChart2,
        title: "Progress Analytics",
        desc: "Track your learning journey.",
    },
    {
        icon: Shield,
        title: "30-Day Money Back",
        desc: "Full refund within 30 days.",
    },
];

export const TESTIMONIALS = [{
        name: "Anh Khoa Pham",
        role: "Front-end Dev at Tiki",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
        text: "Edujar completely changed my career trajectory. The React & Node course gave me the exact skills I needed to land my first dev job at Tiki within 4 months.",
        stars: 5,
        course: "Full-Stack Web Dev",
    },
    {
        name: "Bich Ngoc Tran",
        role: "UX Designer at VNG",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format",
        text: "The UI/UX course quality is on par with Coursera — but explained in Vietnamese context. I got promoted 3 months after finishing it.",
        stars: 5,
        course: "UI/UX Design Mastery",
    },
    {
        name: "Thanh Long Nguyen",
        role: "Data Analyst at Momo",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&auto=format",
        text: "The ML course is incredibly hands-on. Real datasets, real projects. My instructor responded to my question within 2 hours.",
        stars: 5,
        course: "Machine Learning & AI",
    },
];

export const CATEGORIES = [
    "Development", "Design", "Data Science", "Business", "Cybersecurity", "Marketing",
];

export const BADGE_COLORS = {
    Bestseller: "bg-status-warningStrong/10 text-status-warning border-status-warningStrong/20",
    Hot: "bg-status-danger/10 text-status-danger border-status-danger/20",
    New: "bg-status-successStrong/10 text-status-success border-status-successStrong/20",
};
